inherit_gem:
  relaxed-rubocop: .rubocop.yml

inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3
  NewCops: enable
  UseCache: false
  DefaultFormatter: progress
  Exclude:
    - "bin/*"
    - "**/rubocop"
    - "**/vendor/bundle/**/*"
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

Metrics/BlockLength:
  Exclude:
    - Gemfile
