= Makeabox -- Rails Application

:doctype: book
:toc:
:sectnums:
:toclevels: 4
:icons: font

image:https://github.com/kigster/makeabox/actions/workflows/rubyonrails.yml/badge.svg[Unit Tests,link=https://github.com/kigster/makeabox/actions/workflows/rubyonrails.yml]

__This__ is the link:https://makeabox.io/[makeabox application] that generates laser-cut path as a downloadable PDF file.

INFO: It's recently been upgraded to use Rails 7.1 under the hood.

== USAGE

=== Setting up `direnv` is highly recommended:

[source, bash]
----
brew install direnv
# If using BASH:
echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
source ~/.bashrc
direnv allow .
----

=== Install Dependencies

==== Ruby 3.2.2

We prefer to use `rbenv` to manage our rubies.`

[source,bash]
----
brew install rbenv ruby-build
brew upgrade rbenv ruby-build
rbenv install -s 3.2.2
rbenv global 3.2.2
cd makeabox
bundle install -j 12
yarn install -j 12
----

Once you get all the gems installed, its time to verify:

[source, bash]
----
# run the specs
bundle exec rspec

# run rubocop
bundle exec rubocop
----

== Run and Test MakeABox Locally

You can totally start Puma via `bundle rails s`, but we prefer using a wrapper script:

[source, bash]
----
❯ bin/puma-start
[71761] Puma starting in cluster mode...
...
[71761] * Process workers: 6
[71761] * Phased restart available
[71761] * Listening on tcp://0.0.0.0:3000
[71761] Use Ctrl-C to stop
----

If the Puma process does not respond to `Ctrl-C`, use `Ctrl-Z` to push it to the background, and then `kill -9 %1` where `%1` is the job ID given during the suspend event.

[source, bash]
----
^Z
[1]+  Stopped                 bin/puma-start
❯ kill -9 %1
----

The job number appears in the square brackets next to "Stopped". If the number is greater than one, it means you have other background jobs running. Run `jobs -l` to see them.

== Deploying

=== Prerequisites

Before the next step, you need to have the private SSH key that Amazon gave you for your account, so that you can login as the user `ubuntu` and essentially — `root`.

Place this PEM file into a specific location: `${HOME}/.ssh/makeabox.pem` and everything else will be easy.

=== Automatic Deploy

Deploy is provided with Capistrano.

[source,bash]
----
bundle exec cap production deploy --trace
----

== NewRelic Monitoring

* https://one.newrelic.com/nr1-core?account=779492&filters=%28domain%20IN%20%28%27APM%27%2C%20%27EXT%27%29%20AND%20type%20IN%20%28%27APPLICATION%27%2C%20%27SERVICE%27%29%29&state=706dd394-d459-8b6d-4d64-7d26931f0082)


