# frozen_string_literal: true
require 'forwardable'
module Makeabox
  # This class maintains a single global thread per Ruby Process that cleans up old PDFs
  # generated by makeabox controller
  class FileCleaner
    include WithLogging

    SECONDS_TO_KEEP = 60 # we'll delete local files after this many seconds
    SECONDS_TO_SLEEP = 30

    attr_accessor :thread, :temp_files

    extend Forwardable
    def_delegators :@temp_files, :size, :<<, :pop, :empty?

    def initialize
      self.temp_files = Queue.new
      self.thread     =
        Thread.new do
          loop do
            gc! || sleep(SECONDS_TO_SLEEP)
          end
        end
    end

    def <<(file)
      temp_files << file
    end

    def gc!
      return if temp_files.empty?

      file = temp_files.pop
      return if file.nil?
      return unless File.exist?(file)

      fs  = File::Stat.new(file)
      age = Time.now.to_f - fs.ctime.to_f
      logging('garbage collecting file', file: file, age: age) do |extra|
        inspect_file(file, age, extra)
      end
    rescue StandardError => e
      Rails.logger.error('FileCleaner.gc!', error: e.message)
    end

    protected

    def inspect_file(f, age, extra)
      if age < SECONDS_TO_KEEP
        # back onto the queue
        extra[:message] += ', but its too early'
        temp_files << f
        false
      else
        extra[:message] += ', and its gone'
        # now we can delete it
        FileUtils.rm_f(f)
        true
      end
    end
  end
end
