#!/usr/bin/env bash

set +e

pidfile=$(grep pid config/puma.rb | \
    sed "s/'//g" | \
    awk '{print $2}')

if [[ -f ${pidfile} ]]; then
  pid=$(cat ${pidfile} 2>/dev/null)

  [[ ${pid} ]] && {
    kill ${pid} 2>/dev/null
    sleep 1
    kill -9 ${pid} 2>/dev/null
  }
fi

export RAILS_ENV=production
bundle exec rake assets:precompile 1>/dev/null &
bundle exec puma -C config/puma.rb --tag makeabox -e ${RAILS_ENV:-production} &


